export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const SAVE_USER_DETAIL_REQUEST = "SAVE_USER_DETAIL_REQUEST";
export const SAVE_USER_DETAIL_SUCCESS = "SAVE_USER_DETAIL_SUCCESS";
export const SAVE_USER_DETAIL_FAILURE = "SAVE_USER_DETAIL_FAILURE";
